export enum RolesEnum {
  ROLE_CITIZEN = 'ROLE_CITIZEN',
  ROLE_DRIVER = 'ROLE_DRIVER',
  ROLE_MUNICIPAL_ADMINISTRATOR = 'ROLE_MUNICIPAL_ADMINISTRATOR',
  ROLE_SYSTEM_ADMINISTRATOR = 'ROLE_SYSTEM_ADMINISTRATOR'
}
