export interface RouteResponse {
  id: string | null;
  districtId: string | null;
  vehicleId: string | null;
  driverId: string | null;
  routeType: string | null;
  status: string | null;
  scheduledStartAt: string | null;
  scheduledEndAt: string | null;
  startedAt: string | null;
  completedAt: string | null;
  totalDistance: string | null;
  estimatedDuration: string | null;
  collectionDuration: string | null;
  returnDuration: string | null;
  actualDuration: string | null;
  currentLatitude: string | null;
  currentLongitude: string | null;
  lastLocationUpdate: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}
